# R3M Configuration for Hugging Face Spaces
server:
  port: 7860
  host: "0.0.0.0"
  threads: 4
  enable_cors: true
  cors_origins: ["*"]

models:
  embedding:
    path: ""
    batch_size: 32
    max_length: 256
    normalize: true
    cache_size: 1000

logging:
  level: "info"
  format: "text"
  output: "/app/data/logs/r3m.log"
  max_size: "10MB"
  max_files: 5

storage:
  data_path: "/app/data"
  cache_path: "/app/data/cache"
  log_path: "/app/data/logs"
  temp_path: "/tmp/r3m"

performance:
  max_memory: "2GB"
  cache_memory: "512MB"
  max_threads: 4
  batch_timeout: 10 