name: Deploy R3M to Hugging Face Spaces

on:
  push:
    branches: [ main, master, testings2 ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Hugging Face CLI
      run: pip install huggingface_hub
      
    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Create Space if it doesn't exist
        if ! curl -s -H "Authorization: Bearer $HF_TOKEN" \
          "https://huggingface.co/api/spaces/anorohit/r3m-api" > /dev/null; then
          echo "Creating new Space..."
          curl -X POST \
            -H "Authorization: Bearer $HF_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "sdk": "docker",
              "title": "R3M Document Processing API",
              "description": "High-performance C++ document processing system"
            }' \
            "https://huggingface.co/api/spaces"
        fi
        
        # Copy files to Space
        echo "Copying files to Space..."
        cp -r deploy/r3m-huggingface/* .
        
        # Use Hugging Face CLI to upload files
        echo "Uploading files to Hugging Face Space..."
        huggingface-cli upload anorohit/r3m-api . --token $HF_TOKEN 