# name: Deploy R3M to Cloudflare Workers

# on:
#   push:
#     branches: [ testings2 ]
#   workflow_dispatch:

# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'
        
#     - name: Install Wrangler v4
#       run: npm install -g wrangler@latest
      
#     - name: Deploy to Cloudflare Workers
#       working-directory: deploy/r3m-cloudflare
#       run: wrangler deploy src/index.js --name r3m-api --compatibility-date 2025-08-04
#       env:
#         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#         CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 