name: Deploy R3M to Railway

on:
  push:
    branches: [ testings2 ]
  workflow_dispatch:

jobs:
  deploy-railway:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Railway
      uses: railway/deploy@v1
      with:
        service: r3m-api
        token: ${{ secrets.RAILWAY_TOKEN }} 