name: Deploy R3M to Railway

on:
  push:
    branches: [ testings2 ]
  workflow_dispatch:

jobs:
  deploy-railway:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      run: |
        # Set Railway token
        mkdir -p ~/.railway
        echo ${{ secrets.RAILWAY_TOKEN }} > ~/.railway/token
        
        # List existing services
        railway service list || echo "No services found"
        
        # Deploy without specifying service name (Railway will auto-detect)
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 