name: Deploy R3M to Railway

on:
  push:
    branches: [ testings2 ]
  workflow_dispatch:

jobs:
  deploy-railway:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up --service r3m-api
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 