name: Deploy R3M to Cloudflare Workers

on:
  push:
    branches: [ testings2 ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: deploy/r3m-cloudflare/package-lock.json
        
    - name: Install dependencies
      working-directory: deploy/r3m-cloudflare
      run: npm ci
      
    - name: Deploy to Cloudflare Workers
      working-directory: deploy/r3m-cloudflare
      run: npx wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 