# R3M Production Configuration - Core Document Processing Pipeline
server:
  port: 8080
  host: "0.0.0.0"
  threads: 8

logging:
  level: "info"
  format: "json"
  output: "/app/data/logs/r3m.log"

# Document Processing Pipeline Configuration (Core Formats Only)
document_processing:
  # Supported file extensions (core formats only)
  supported_extensions:
    plain_text: [".txt", ".md", ".mdx", ".conf", ".log", ".json", ".csv", ".tsv", ".xml", ".yml", ".yaml"]
    pdf: [".pdf"]
    html: [".html", ".htm"]
  
  # Processing settings
  max_file_size: "500MB"
  max_text_length: 5000000  # 5M characters
  enable_parallel_processing: true
  worker_threads: 16
  
  # OPTIMIZED BATCH PROCESSING SETTINGS
  batch_size: 32  # Optimal batch size for production
  max_workers: 16  # Optimal worker count for production
  
  # OPTIMIZED PARALLEL PROCESSING CONFIGURATION
  enable_optimized_thread_pool: true
  enable_thread_affinity: true
  enable_work_stealing: true
  enable_memory_pooling: true
  
  # SIMD OPTIMIZATION CONFIGURATION
  enable_simd_optimizations: true
  enable_avx2: true
  enable_avx512: true
  enable_neon: true
  
  # CHUNKING CONFIGURATION - OPTIMIZED!
  enable_chunking: true
  
  # Text processing
  text_processing:
    encoding_detection: true
    default_encoding: "utf-8"
    remove_html_tags: true
    normalize_whitespace: true
    extract_metadata: true
  
  # Quality filtering (advanced document processing feature)
  quality_filtering:
    enabled: true
    min_content_quality_score: 0.4      # Higher threshold for production
    min_information_density: 0.15       # Higher threshold for production
    min_content_length: 100             # Higher minimum for production
    max_content_length: 5000000         # Higher maximum for production
    filter_empty_documents: true        # Filter out empty documents
    filter_low_quality_documents: true  # Filter out low-quality documents
    
    # Quality assessment algorithm weights
    quality_weights:
      length_factor: 0.25               # Adjusted for production
      word_diversity_factor: 0.35       # Higher weight for diversity
      sentence_structure_factor: 0.25   # Higher weight for structure
      information_density_factor: 0.15  # Lower weight for density
    
    # Information density calculation weights
    density_weights:
      unique_word_ratio: 0.45           # Higher weight for unique words
      technical_term_density: 0.35      # Higher weight for technical terms
      sentence_complexity: 0.20         # Lower weight for complexity
    
    # Quality calculation thresholds
    quality_thresholds:
      length_normalization: 2000        # Higher normalization for production
      word_diversity_normalization: 6   # Adjusted for production
      sentence_normalization: 15        # Higher threshold for production
      technical_term_normalization: 12  # Higher threshold for production
      sentence_complexity_normalization: 120  # Higher threshold for production
      whitespace_threshold: 0.15        # Higher threshold for production
  
  # Pipeline stages (core processing only)
  pipeline_stages:
    - "file_validation"
    - "text_extraction"
    - "text_cleaning"
    - "metadata_extraction"
    - "quality_assessment"
    - "filtering"
    - "chunking"

# Chunking Configuration (Advanced Document Segmentation) - OPTIMIZED!
chunking:
  # Tokenizer settings
  tokenizer:
    type: "basic"                    # Tokenizer type: basic, bpe, sentencepiece
    max_tokens: 8192                 # Maximum tokens per chunk
    token_limit: 2048                # Target token limit for chunks
    chunk_overlap: 0                 # Token overlap between chunks (0 for clean combinations)
  
  # OPTIMIZED CHUNK SIZE SETTINGS
  chunk_sizes:
    blurb_size: 100                  # Size for extracting blurbs (first sentence)
    mini_chunk_size: 150             # Mini-chunk size for multipass mode
    large_chunk_ratio: 4             # Number of regular chunks per large chunk
    chunk_min_content: 256           # Minimum content tokens per chunk
  
  # OPTIMIZED METADATA SETTINGS
  metadata:
    include_metadata: true            # Include document metadata in chunks
    max_metadata_percentage: 0.25    # Maximum metadata percentage (25%)
    skip_metadata_in_chunk: false    # Skip metadata in chunk content
  
  # OPTIMIZED CHUNKING FEATURES
  enable_multipass: true             # Enable multi-pass indexing
  enable_large_chunks: true          # Enable large chunk generation
  enable_contextual_rag: true        # Enable contextual RAG features
  contextual_rag_reserved_tokens: 512 # Reserved tokens for RAG context
  
  # OPTIMIZED TOKEN PROCESSING
  enable_token_caching: true         # Enable token caching for performance
  enable_string_view_optimization: true # Enable string_view optimizations
  enable_preallocation: true         # Enable vector preallocation
  enable_move_semantics: true        # Enable move semantics for efficiency

# Engine configuration
engine:
  # Performance settings
  max_memory_mb: 8192
  cache_memory_mb: 2048
  batch_timeout_seconds: 60
  
  # OPTIMIZED THREAD POOL SETTINGS
  thread_pool:
    fallback_threads: 8                 # Higher fallback for production
    hardware_concurrency_fallback: 8    # Higher fallback for production
  
  # Monitoring settings
  enable_metrics: true
  metrics_interval_seconds: 10

# Storage paths
storage:
  data_path: "/app/data"
  temp_path: "/tmp/r3m"
  cache_path: "/app/data/cache"

# Test configuration (for production testing)
testing:
  # Test file creation parameters
  test_files:
    large_file_count: 16                # More files for production testing
    large_file_lines: 1000              # More lines for production testing
    enhancement_file_count: 24          # More files for production testing
    enhancement_file_lines: 600         # More lines for production testing
  
  # Test performance parameters
  performance:
    efficiency_thread_count: 16         # Higher thread count for production
    test_batch_size: 8                  # Larger batch size for production testing
    test_max_workers: 16                # More workers for production testing 